import { ArrowRight, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { reportSections } from '../data/reportData'
import { useArihant } from '../context/ArihantContext'
import type { FieldDefinition } from '../types'

function SectionField({ sectionKey, field }: { sectionKey: string; field: FieldDefinition }) {
  const { sectionValues, updateSectionValue } = useArihant()
  const value = sectionValues[sectionKey]?.[field.key] || ''
  if (field.type === 'group') return <fieldset className="rounded-xl border border-slate-200 p-4 md:col-span-2"><legend className="px-1 text-xs font-bold uppercase tracking-[0.16em] text-slate-500">{field.label}</legend><div className="mt-2 grid gap-4 md:grid-cols-2">{field.childFields?.map(child => <SectionField key={child.key} sectionKey={sectionKey} field={child} />)}</div></fieldset>
  return <label className="block"><span className="mb-2 block text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">{field.label}</span>{field.type === 'dropdown' ? <select value={value} onChange={event => updateSectionValue(sectionKey, field.key, event.target.value)} className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-[#3b5998] focus:ring-4 focus:ring-blue-100"><option value="">Choose...</option>{field.options?.map(option => <option key={option} value={option}>{option}</option>)}</select> : <input type={field.type === 'date' ? 'date' : 'text'} value={value} onChange={event => updateSectionValue(sectionKey, field.key, event.target.value)} placeholder={field.type === 'date' ? undefined : 'Enter details'} className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-[#3b5998] focus:ring-4 focus:ring-blue-100" />}</label>
}

export function ImmovablesPage() {
  const [selectedIndex, setSelectedIndex] = useState(0)
  const { populateWithMockAi } = useArihant()
  const section = reportSections[selectedIndex]
  return <div><div className="border-b border-slate-100 pb-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#3b5998]">Summary</p><h2 className="mt-2 text-3xl font-bold text-slate-900">Immovables</h2><p className="mt-2 text-sm text-slate-500">Capture the property record section by section.</p></div><div className="mt-6 grid gap-5 lg:grid-cols-[260px_1fr]"><div className="overflow-x-auto lg:overflow-visible"><p className="mb-3 text-xs font-bold uppercase tracking-[0.16em] text-slate-400">Sections</p><div className="flex gap-2 lg:block">{reportSections.map((item, index) => <button type="button" key={item.eventKey} onClick={() => setSelectedIndex(index)} className={`whitespace-nowrap rounded-xl px-3 py-2.5 text-left text-sm transition lg:flex lg:w-full lg:items-center lg:gap-2 ${selectedIndex === index ? 'bg-[#e9ecef] font-bold text-[#3b5998]' : 'text-slate-600 hover:bg-slate-50'}`}><span className="font-mono text-xs text-slate-400">{item.eventKey}.</span>{item.label}</button>)}</div></div><div className="rounded-2xl border border-slate-100 bg-[#fffdf8] p-5 md:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-400">Section {section.eventKey}</p><h3 className="mt-2 text-xl font-bold text-slate-800">{section.label}</h3></div><button type="button" onClick={populateWithMockAi} className="inline-flex items-center gap-2 rounded-xl border border-blue-200 bg-blue-50 px-3 py-2 text-xs font-bold text-[#3b5998] hover:bg-blue-100"><Sparkles size={15} /> Fill sample AI data</button></div><div className="mt-6 grid gap-4 md:grid-cols-2">{section.fields.map(field => <SectionField key={field.key} sectionKey={section.eventKey} field={field} />)}</div><div className="mt-6 flex flex-wrap justify-end gap-3"><button type="button" className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-600">Save draft</button><button type="button" onClick={() => setSelectedIndex(Math.min(selectedIndex + 1, reportSections.length - 1))} className="rounded-xl bg-[#1a0dab] px-4 py-2.5 text-sm font-semibold text-white">Continue section <ArrowRight size={16} className="ml-1 inline" /></button></div></div></div></div>
}
